### ISSUE TITLE
`[[ ]]` syntax in code block trated as alias

### ISSUE THREAD

**Issue by joapuiib** [EddyLuten/mkdocs-alias-plugin#13]
Hi,

Using this plugin, the following code would try to treat `[['column1', 'column2']]` as an alias.

__Markdown content__:
````md
```python
improt pandas as pd

df = pd.Dataframe(...)

df = df[['column1`', 'column2']]
```
````

The final rendering will be OK, since the alias is not defined, but a WARNING is shown.
```
WARNING -  Alias ''column1`', 'column2'' not found in 'page.md'
```

Could it be convenient that this plugin doesn't try to look for aliases in `<pre>` or `<code>` blocks?

**Comment by joapuiib** [comment]
I've been playing with the plugin a bit, and the main challenge I see is that it is difficult to tell which aliases are inside a `<pre>` or `</code>` block, since the current implementation replaces all alias occurrences directly in the markdown content directly.

https://github.com/EddyLuten/mkdocs-alias-plugin/blob/33546df56805e2cd324a7dcb16348ae44b918fd8/alias/plugin.py#L161C5-L174C10

Maybe this could be solved by looking for the aliases in the HTML [`on_post_page()`](https://www.mkdocs.org/dev-guide/plugins/#on_post_page), after Markdown is parsed.

In that way, we can tell which aliases are inside specific blocks.

**Comment by EddyLuten** [comment]
Hi @joapuiib, would [escaping](https://github.com/EddyLuten/mkdocs-alias-plugin/blob/main/README.md#escaping-aliases-escape-syntax) work here? I added this feature for a similar use case in shell scripts in #1

**Comment by joapuiib** [comment]
It does work! I thought I tried it. :man_facepalming: 

Thanks for your answer. and sorry for the inconvenience.
