### ISSUE TITLE
Option to use relative url

### ISSUE THREAD

**Issue by SimonDelmas** [EddyLuten/mkdocs-alias-plugin#3]
I use your plugin for a project documentation and I really enjoy it!

I recently encountered a problem with the alias link, as the url used for replacement is an absolute url. 
Indeed my documentation site is hosted on a specific route: https://my_site.net/my_project/documentation/
In this case using an absolute url resulted in a link that points to the wrong destination :
https://my_site.net/my_alias instead of https://my_site.net/my_project/documentation/my_alias

I would like to add an option to make the link relative to the current page to fix this issue.

**Comment by EddyLuten** [comment]
Hi, thanks for reporting this issue, @SimonDelmas! I noticed that you closed your PR. Is this issue still valid?

**Comment by SimonDelmas** [comment]
Hi, I did a PR yesterday to propose you an option to fix my issue, but I went too fast and the patch did not correct my problem... I have just submitted another cleaner proposal.

**Comment by EddyLuten** [comment]
Thanks, your solution could be helpful for a wide variety of folks. I will push this new feature out in the next minor release after I update the readme, etc.

Thanks for your contribution!
