### ISSUE TITLE
Support for page anchors.

### ISSUE THREAD

**Issue by shaloo** [EddyLuten/mkdocs-alias-plugin#6]
If I create an alias for a page, is there a way to cross-reference a page anchor using an alias?
For e.g., 

```test.md```

Refer to the  [[devguide-page-ref|developer guide]]#install-section for more details

```devguide.md```

---
alias: devguide-page-ref

---

# Some Title

Yada Yada Yada

## Installation 

Yada Yada Yada

## Debug

Yada Yada Yada

I tried via ```[[devguide-page-ref|developer guide]]#install-section``` as well as ```[[devguide-page-ref#install-section|developer guide]]``` But the generated link is incorrect.

**Comment by EddyLuten** [comment]
The plugin currently doesn't support anchors, but adding support should be easy enough. I will update this issue with more info once it's complete.

**Comment by EddyLuten** [comment]
Support for page anchors is now available in version 0.6.0 available on PyPI. The syntax is:

```md
[[devguide-page-ref#install-section|developer guide]]
```

This would link to `devguide.md#install-section`.

I've kept the anchor and the alias together since it's the bit that identifies which page to link to.

**Comment by shaloo** [comment]
Thanks @EddyLuten for the prompt response!
