### ISSUE TITLE
specific words cause the plugin to fail

### ISSUE THREAD

**Issue by usulpt** [EddyLuten/mkdocs-alias-plugin#7]
hello.

whenever I use the word "context" (upper or lowercase) in an alias definition under the frontmatter YAML of an mkdocs.yml file, the build process fails with the following error:

    meta_data['alias']['text']
    ~~~~~~~~~~~~~~~~~~^^^^^^^^

I'm using Python 3.11, mkdocs 1.5.3 with mkdocs-material 9.4.1

thanks!
Jorge

**Comment by EddyLuten** [comment]
Interesting, I'll take a look!

**Comment by usulpt** [comment]
it was really weird because I work with a few hundred files in the same folder and I was processing them automatically through another tool that inserts names of files as aliases in the same file. and everything was running fine until it hit a file called "somethingcontext.md". tested it with several files with the same results and ended up having to rename the alias to something like "ctx". maybe there's a reserved keyword, beats me, but the plugin is really useful (great work!) so I wanted to give you a heads-up anyway :)

**Comment by usulpt** [comment]
pretty dumb, yeah, and I should know because I made several of those in my programming life :) I hadn't even checked the code before I opened the issue, shame on me.

just tested 0.7.1 and it works fine now! thank you very much for the fix and for doing it lightning-fast!

**Comment by EddyLuten** [comment]
Awesome, thanks for the report!1
